server:
  port: 8080
spring:
  name: backend-client-service
springdoc:
  swagger-ui:
    path: swagger-ui.html
logging:
  level:
    root: INFO
backend-client-service:
  client:
    products-service-url: ${PRODUCTS_SERVICE_PATH:http://localhost:8081}
    tariffs-service-url: ${TARIFFS_SERVICE_PATH:http://localhost:8082}