version: '3'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    hostname: postgres
    ports:
      - '5555:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql
      - postgresql_data:/var/lib/postgresql/data
    restart: always
    networks:
      - my-network

volumes:
  postgresql_data:
    driver: local

networks:
  my-network:
    driver: bridge